### PR TITLE
fix: Include multi-line commits in the changelog

### LINKED ISSUE #3: Multiline commit messages are dropped
Hi! Thanks for the useful action!

I noticed that some of my commits don't make it to the changelog. I found that it happens to all commits with multiline messages. I suspect that the problem is in the commit regex:

https://github.com/ardalanamini/auto-changelog/blob/e2ed19a3f16dd561a623e4fd6ecd9a907c4fd734/src/changelog.ts#L95

But I'm not sure how to fix it. Could you look into it?

### PR DESCRIPTION
**Pull request by laughedelic**
Use `\n?` instead of `$` to match potentially multiline messages, but still capture only the first line.

Hopefully fixes #3.

### CODE REVIEW

**Comment by ardalanamini** [comment]
@laughedelic Hi, thanks for the contribution

It seems the new regex doesn't match commits correctly regardless of being single-line or multi-line 🤔

**Comment by ardalanamini** [comment]
@laughedelic Let me know if current changes work in your case as well

**Comment by laughedelic** [comment]
Yes, thanks for fixing it!

**Comment by laughedelic** [comment]
I mean, yes, I think your change makes sense, but I haven't tested it in my repository. I don't know how to test an unreleased action if that's what you were asking about.

**Pull request merged**
